const express    = require("express");
const router     = express.Router();
const controller = require("../controllers/admin-controller");
const aiController = require("../controllers/ai-controller");
const isAdmin = require("../middleware/isAdmin");

router.use(isAdmin);


router.get("/dashboard",                     controller.getDashboard);
router.get("/profile",                       controller.getProfile);
router.post("/profile/update",               controller.updateProfile);
router.get("/edit-profile",                  controller.getEditProfile);
router.post("/edit-profile",                 controller.updateProfile);
router.get("/users",                         controller.getUsers);
router.post("/users/change-role",            controller.changeRole);
router.get("/users/:userId/profile",         controller.getUserProfile);
router.get("/users/:userId/courses", controller.getUserCourses);
router.get("/users/:userId/challenges", controller.getUserChallenges);
router.post("/users/toggle-suspend/:userId", controller.toggleSuspend);
router.post("/users/delete/:userId", controller.deleteUser);
router.post("/users/:userId/block", controller.blockInstructor);
router.post("/users/:userId/unblock", controller.unblockInstructor);
router.get("/manage-challenges",             controller.getChallenges);
router.post("/manage-challenges/:id/delete", controller.deleteChallenge);
router.post("/manage-challenges/:id/restore", controller.restoreChallenge);
router.post("/manage-challenges/:id/permanent-delete", controller.permanentlyDeleteChallenge);
router.get("/instructor-applications", controller.getInstructorApplications);
router.post("/instructor-applications/:userId/approve", controller.approveInstructor);
router.post("/instructor-applications/:userId/reject", controller.rejectInstructor);
router.get("/create-challenge",              controller.getCreateChallenge);
router.post("/create-challenge", controller.postCreateChallenge);
router.get("/challenges/:id/edit", controller.getEditChallenge);
router.post("/challenges/:id/edit", controller.postEditChallenge);
router.post("/generate-challenge", aiController.generateChallengeDraft);
router.get("/course-applications", controller.getCourseApplications);
router.post("/course-applications/:courseId/approve", controller.approveCourse);
router.post("/course-applications/:courseId/reject", controller.rejectCourse);
router.get("/courses/:courseId/content", controller.previewCourseContent);
router.get("/courses/:courseId/students", controller.getAdminCourseStudents);
module.exports = router;